// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buwznjsbimqzpalklabm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1d3puanNiaW1xenBhbGtsYWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTc5NDEsImV4cCI6MjA3Mzk3Mzk0MX0.x5P96w8QyRpDW5-H7MiE-jvsEvxkVSHeFmDN_Dgh1KY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});